var prompts = [
    "@ reminds you most of what animal?",
    "If @ was a movie genre, what would they be?",
    "If @ was a breakfast cereal, what would they be?",
    "What would a documentary about @ be titled?",
    "If @ and @ formed a band, what would it be called?",
    "Describe @'s dream house",
    "What will it say on @'s tombstone",
    "If @ sued @, what would be the reason",
    "What would be the name of @'s podcast",
    "@ starts a store, selling what?",
    "What is @ hiding in their browser history?",
    "What was the last video @ watched?",
    "What does @ do to get rid of stress?",
    "What is something @ is obssessed with?",
    "What three words best describe @?",
    "What is the most useful thing @ owns?",
    "What popular thing annoys @?",
    "If @ had intro music, what would it be?",
    "If @ taught a class, what would it be in?",
    "If @ had to spend the weekend at @'s house, what would they do?",
    "If @ got @ a gift, what would it be?",
    "What do @ and @ have in common?",
    "What would @ wear to a fashion show?",
    "What is @'s go to curse word?",
    "What is @'s catchphrase?",
    "What does @ say to @ most frequently?",
    "What is on @'s bucket list",
    "What will @ never do?",
    "What is @'s favorite TV show?",
    "If @ was the host of a reality TV show, what would it be about?",
    "What is the last song @ listened to?",
    "What is @'s go to restaurant order?",
    "What would @ cook for a dinner party?",
    "What is the coolest thing @ has done?",
    "What is at the top of @'s grocery list?",
    "If @ and @ were in a movie together, what would the title be?",
    "@ and @ are cast in a movie remake, what movie would it be?",
    "What game has @ played the most",
    "If @ wrote the next ten commandments, what would the first one be?",
    "What did @ last search for online?",
    "If @ had children, what will their parenting catchphrase be?",
    "In a movie about @, who would be the lead?",
    "What would happen to @ during the apocalypse?",
    "What is @'s ideal vacation?",
    "What movie quote best describes @",
    "If @ changed their profession to an area they haven't shown interest in, what would it be?",
    "What smell is @'s favorite?",
    "What conspiracy theory is @ most likely to believe in?",
    "Which national park would @ like to visit most?",
    "If @ had a different first name, what would it be?",
]
module.exports = {
    prompts
}